import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

// Your live Supabase connection keys
const supabaseUrl = 'https://figpskarzodfeiaulmfa.supabase.co';
const supabaseKey = 'sb_publishable_OlHhzoYHI7lz84y-LSNFOg_S0s3EH0C';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
    
      // Connect the app to your database
        await Supabase.initialize(
            url: supabaseUrl,
                anonKey: supabaseKey,
                  );
                    
                      runApp(const RewardApp());
                      }

                      class RewardApp extends StatelessWidget {
                        const RewardApp({super.key});

                          @override
                            Widget build(BuildContext context) {
                                return MaterialApp(
                                      title: 'Task Rewards',
                                            theme: ThemeData(
                                                    primarySwatch: Colors.blue,
                                                          ),
                                                                home: const EarnScreen(),
                                                                      debugShowCheckedModeBanner: false,
                                                                          );
                                                                            }
                                                                            }

                                                                            class EarnScreen extends StatefulWidget {
                                                                              const EarnScreen({super.key});

                                                                                @override
                                                                                  State<EarnScreen> createState() => _EarnScreenState();
                                                                                  }

                                                                                  class _EarnScreenState extends State<EarnScreen> {
                                                                                    final _supabase = Supabase.instance.client;
                                                                                      
                                                                                        // Test User ID
                                                                                          final String testUserId = '00000000-0000-0000-0000-000000000000'; 

                                                                                            @override
                                                                                              Widget build(BuildContext context) {
                                                                                                  return Scaffold(
                                                                                                        appBar: AppBar(title: const Text('Earn Coins')),
                                                                                                              body: ListView(
                                                                                                                      padding: const EdgeInsets.all(16.0),
                                                                                                                              children: [
                                                                                                                                        // Real-Time Wallet Balance Card
                                                                                                                                                  StreamBuilder<List<Map<String, dynamic>>>(
                                                                                                                                                              stream: _supabase.from('users').stream(primaryKey: ['id']).eq('id', testUserId),
                                                                                                                                                                          builder: (context, snapshot) {
                                                                                                                                                                                        // Catch and display internet/database errors
                                                                                                                                                                                                      if (snapshot.hasError) {
                                                                                                                                                                                                                      return Card(
                                                                                                                                                                                                                                        color: Colors.red[50],
                                                                                                                                                                                                                                                          child: Padding(
                                                                                                                                                                                                                                                                              padding: const EdgeInsets.all(16.0), 
                                                                                                                                                                                                                                                                                                  child: Text('Error: ${snapshot.error}', style: const TextStyle(color: Colors.red, fontSize: 12))
                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                              if (!snapshot.hasData) {
                                                                                                                                                                                                                                                                                                                                                                                              return const Card(
                                                                                                                                                                                                                                                                                                                                                                                                                color: Colors.blueAccent,
                                                                                                                                                                                                                                                                                                                                                                                                                                  child: Padding(
                                                                                                                                                                                                                                                                                                                                                                                                                                                      padding: EdgeInsets.all(24.0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          child: Center(child: CircularProgressIndicator(color: Colors.white)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // Safely extract balance if the row exists
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    final userData = snapshot.data!.isNotEmpty ? snapshot.data!.first : null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  final balance = userData?['coin_balance'] ?? 0;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return Card(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                color: Colors.blueAccent,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                child: Padding(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  padding: const EdgeInsets.all(24.0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    child: Column(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        children: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const Text('Your Balance', style: TextStyle(color: Colors.white, fontSize: 16)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const SizedBox(height: 8),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Text('$balance Coins', style: TextStyle(color: Colors.white, fontSize: 32, fontWeight: FontWeight.bold)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const SizedBox(height: 20),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Watch Ad Button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ElevatedButton.icon(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  icon: const Icon(Icons.video_library),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              label: const Text('Watch Ad (+10 Coins)'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onPressed: () {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ScaffoldMessenger.of(context).showSnackBar(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const SnackBar(content: Text('Ads coming in the next step!')),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }